zelchip_1/mainApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mainApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('photos/', views.get_photos, name='photos'),
    path('news/', views.get_news, name='news'),
]

zelchip_1/mainApp/models.py
from datetime import timezone, datetime
from django.db import models
from django.utils import timezone


class Menu(models.Model):
    names = models.CharField(max_length=50)
    names_info = models.CharField(max_length=50)

    def __str__(self):
        return self.names


class News(models.Model):
    title_news = models.CharField(max_length=255)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    is_pulished = models.BooleanField(default=True)

    def __str__(self):
        return self.title_news


class Photos(models.Model):
    title = models.CharField(max_length=255)
    photos = models.ImageField(upload_to="photo/%Y/%m/%d")

    def __str__(self):
        return self.title

zelchip_1/mainApp/views.py
import random

from django.shortcuts import render
from .models import *


# Create your views here.

def index(request):
    string = 'Hello, world'
    last_new = News.objects.order_by('-pub_date')[:1][0]
    photo = random.choice(Photos.objects.all())
    context = {'string': string, 'last_new': last_new, 'photo': photo}
    return render(request, 'mainApp/index.html', context)


def detail(request):
    string = 'My name is Bond ' \
             'James Bond'
    context = {'string': string}
    return render(request, 'mainApp/detail.html', context)


def get_news(request):
    news = News.objects.order_by('-pub_date')
    context = {'news': news}
    return render(request, 'mainApp/news.html', context)


def get_photos(request):
    photo = Photos.objects.all()

zelchip_1/mainApp/templates/mainApp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <h1>Detail page</h1>>
    <a> {{ string }} </a>
</head>
<body>

</body>
</html>

zelchip_1/mainApp/templates/mainApp/index.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <title>My page</title>

<p>&nbsp;</p>
<div>
<div class="container">
<div>
    <a href="{% url 'mainApp:detail'%}"><div style="float: left; width: 100px; height: 100px;">О нас</div></a>
    <a href="{% url 'mainApp:news'%}"><div style="float: left; width: 100px; height: 100px;">Новости</div></a>
    <a href="{% url 'mainApp:detail'%}"><div style="float: left; width: 100px; height: 100px;">Контакты</div></a>
    <a href="{% url 'mainApp:photos'%}"><div style="float: left; width: 100px; height: 100px;">Фотографии</div></a>
</div>
</div>


<p><img src="{{photo.photos.url}}" alt="{{photo.title}}" width="160" height="250" /></p>
<div>
<table style="border-collapse: collapse; width: 48.8636%; height: 273px;" border="1">
<tbody>
<tr style="height: 18px;">
<td style="width: 100%; height: 18px;"><strong>{{ last_new.title_news }}:</strong>
<p>&nbsp;</p>
{{ last_new.content }}</td>
</tr>
</tbody>
</table>
</div>

</html>

zelchip_1/mainApp/templates/mainApp/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>

    <h3><strong>News page.</strong></h3>
    {% if news %}
    {% for item in news %}
            <p><strong>{{item.title_news}}</strong></p>
            <p>{{item.pub_date}}</p>
            <p>{{item.content}}</p>
            <p>&nbsp;</p>
    {% endfor %}
    {% else %}
        <p>No news are available.</p>
    {% endif %}
</body>
</html>

zelchip_1/mainApp/templates/mainApp/photos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>