zelchip_1.old/main_/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
   path('', views.index, name='index'),
   path('about/', views.about, name='about'),
]

zelchip_1.old/zelchip_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
       path('', include('main.urls')),
       path('main/', include('main.urls')),
       path('admin/', admin.site.urls),
]

zelchip_1.old/main_/models.py
from django.db import models

# Create your models here.

class Main_barlist(models.Model):
    name = models.CharField(max_length=30)
    urls_field = models.URLField(max_length=200, default='http://')
    
    def __str__(self):
        return self.name

zelchip_1.old/main_/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import *

def index(request):
   name_all = Main_barlist.objects.all()
   name_list = [name_all[i].name for i in range(len(name_all))]
   context = {'name_list': name_list}
   return render(request, 'main/index.html', context)

def about(request):
    return render(request, 'main/about.html')

def contacts(request):
    pass

def manufacture(request):
    pass

def search(request):
    pass

def delivery(request):
    pass

zelchip_1.old/main_/templates/main/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>О нас</title>
</head>
<body>
<h1>About us</h1>
</body>
</html>

zelchip_1.old/main_/templates/main/index.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
    <ul>
    {% for name in name_list %}
<!--        <li><a>{{ name }}</a></li>-->
<!--        <li><a><a href="/polls/{{ name }}/">{{ name }}</a></a></li>-->
        <li><a href="{% url 'main:about' %}">{{ name }}</a></li>
    {% endfor %}
    </ul>
  </body>
</html>